version: '3.4'

services:
  irankhodro:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionString=redis://db:6379
      - Cookie=_ga=GA1.2.1358003064.1677500186; __arcsjs=5f972be930f928f4c60f7b4918a14628; ASP.NET_SessionId=jotwxth5x04xkhh2435g11qg; TS01511309=013f7bf61f5b60225048663e32845ffe61e200da0e1d73fbfed1dc39aac1de9846c005b95449dc80fbed9fb86004ad8c2c6ba9630743d30b5325bd14d3162c15cfcb249b75; _gid=GA1.2.1974302761.1677600537; _gat=1
      - Recepters=#
      - SmtpHost=smtp.gmail.com
      - SmtpPort=587
      - SmtpSenderEmailAddress=#
      - SmtpSenderEmailPassword=#
      - SmtpSenderDisplayName=IranKhodro
      - SmtpMessageSubject=لیست بخشنامه ایران خودرو
    restart: always
    
  db:
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    volumes:
      - dbData:/data

volumes:
  dbData:
     external: false
  